### ISSUE TITLE
onPressSignup breaks the card swap functionality

### ISSUE THREAD

**Issue by acerbetti** [WrathChaos/react-native-login-screen#13]
Hi, thank you for this lib, I cannot understand well how do you set the callback for the signup flow?
Do you have a working example?

thanks

**Comment by WrathChaos** [comment]
Hello @acerbetti,
onPressSignup changes the state of card between `Login` card and `SignUp` cards. That's why I make it optional press function for it. If the dev wants to do some custom stuff when `onPressSignup` is on pressed. 

https://github.com/WrathChaos/react-native-login-screen/blob/635dab01d92324c52d19027410638d4a2061d48e/lib/src/LoginScreen.js#L80

As you can see in the code itself, it simply changes the state to handle SignUp card and Login card.

**Comment by acerbetti** [comment]
thank you for the quick reply, but you can see that the props "onPressSignup" is also passed to the "BottomContainer" overriding the "setCardState" code and breaking the functionality

**Comment by WrathChaos** [comment]
Oh I see. Actually it does not break the functionality, as you can see it just `call` the parent's prop function. That's all, it does not the same `onPressSignup` prop. I guess the `BottomContainer`'s onPressSignup prop should be renamed.

**Comment by WrathChaos** [comment]
Why do you think it breaks the functionality?

**Comment by acerbetti** [comment]
Renaming the props on the BottomContainer should do the trick, but I think that is confusing to use the same callback "onPressLogin" on both login and signup flow. 

Broken functionality is because if I pass the props onPressSignup to the LoginScreen, the toggle is not responding anymore

**Comment by WrathChaos** [comment]
Oh, I will fix that ASAP then. I did not know that. I have a plan to re-write the whole library with Typescript, I will also fix this with that. 

Thank you for the contribution @acerbetti :) I believe I can make it tomorrow.

**Comment by WrathChaos** [comment]
Hello @acerbetti,
I think I've fixed this issue on the newest version. I'm sorry it took some time but at least it works great now :)
Please check the new version:

## [Release 2.0.3 🥳](https://github.com/WrathChaos/react-native-login-screen/releases/tag/2.0.3)
